apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-query-consumer
spec:
  selector:
    matchLabels:
      role: service-query-consumer
  replicas: 1
  template:
    metadata:
      labels:
        role: service-query-consumer
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: service-query-consumer
          image: lovelacers/base-consumer
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: SERVICE_NAME
              value: service-query
            - name: CONSUMER_GROUP
              value: service-query-group
            - name: DURABLE_NAME
              value: service-query-consumer
            - name: STREAM_LIST
              value: service-product
            - name: FILTER_SUBJECTS
              value: "service-product.CreateProduct,service-product.UpdateProduct,service-product.CreateMedia,service-product.DeleteProduct"
            - name: DATABASE_NAME
              value: service_query
            - name: DATABASE_USER
              value: marketplace   
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HANDLER_WEAVIATE_HOST
              valueFrom:
                configMapKeyRef:
                  name: weaviate-cluster-config
                  key: host
            - name: HANDLER_EMBEDDING_HOST
              valueFrom:
                configMapKeyRef:
                  name: embedding-config
                  key: host                           
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password              
            - name: NATS_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: nats-cluster-config
                  key: hosts 
                  
          resources:
            requests:
              cpu: "10m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"   