apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-chat
  template:
    metadata:
      labels:
        role: service-chat
    spec:
      containers:
        - name: service-chat
          image: lovelacers/service-chat
          env:
            - name: NODE_ENV
              value: "development"                       
            - name: REDIS_CHAT_HOST
              value: redis://redis-chat:6379
            - name: REDIS_RATELIMIT_HOST
              value: redis://redis-limiter:6379                     
            - name: AGENT_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-key-secret
                  key: key

          resources:
            requests:
              cpu: "10m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"      
---
apiVersion: v1
kind: Service
metadata:
  name: service-chat
spec:
  selector:
    role: service-chat
  ports:
    - name: service-chat
      protocol: TCP
      port: 8010
      targetPort: 8010
