apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-seller
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-seller
  template:
    metadata:
      labels:
        role: service-seller
    spec:
      containers:
        - name: service-seller
          image: lovelacers/service-seller
          env:
            - name: NODE_ENV
              value: development                                                                                                                
            - name: DATABASE_NAME
              value: service_seller       
            - name: DATABASE_USER
              value: marketplace 
            - name: TOKEN_EXPIRATION
              value: "7d" 
            - name : REDIS_RATELIMIT_URL
              value: "redis://redis-limiter:6379"
            - name: AGENT_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-key-secret
                  key: key             
            - name: DATABASE_HOST  
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master  
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port                                     
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password

          resources:
            requests:
              cpu: "10m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"        
---
apiVersion: v1
kind: Service
metadata:
  name: service-seller
spec:
  selector:
    role: service-seller
  ports:
    - name: service-seller
      protocol: TCP
      port: 8000
      targetPort: 8000
